### ISSUE TITLE
Publish the app on F-Droid app store

### ISSUE THREAD

**Issue by Pranab009** [Sav22999/sav-pdf-viewer-pro#12]
I'm download from Fdroid and It takes too much space 22mb before install and 33mb after install.
You say it is little (6.9mb only)this is perfect but 33mb is too much for just pdf viewer.
![Screenshot_20210926-100056](https://user-images.githubusercontent.com/65340361/134816197-8fea09cc-b777-4909-8def-b09f9a7b0ac5.png)

**Comment by Sav22999** [comment]
@Pranab009 Hi! Thanks for the report... so, the installation package size is 6.9MB 
![immagine](https://user-images.githubusercontent.com/32335378/134816308-fd8ad736-b75b-4a27-8ea0-99b789e13b9b.png)
 You can see it on Google Play https://play.google.com/store/apps/details?id=com.saverio.pdfviewer&hl=en
Then, the app size depends on your Android version and OS optimisation, probably. On my device, for example, the app size is 18.56MB

You can see the user data (so the data saved in the app (like the positions, etc.) is just 119KB).

I'm sorry for this inconvenience

**Comment by Sav22999** [comment]
In addition, please, could you provide me the download link of F-Droid? I've published the app just on Google Play, Huawei AppGallery and Amazon AppStore

**Comment by Pranab009** [comment]
Not actually from Fdroid. It is izzydroid
https://apt.izzysoft.de/fdroid/repo/com.saverio.pdfviewer

**Comment by Sav22999** [comment]
I can't see that page, actually. Anyway, I suggest you to try to install by yourself compiling the app.
As I said, I can't manage version publish on IzzySoft :/

**Comment by Pranab009** [comment]
I'm not a Devloper. Don't know about compiling.

When it released on Fdroid?

**Comment by Sav22999** [comment]
@Pranab009 probably it won't

**Comment by Pranab009** [comment]
But why?
Please add it on Fdroid.

**Comment by ShareASmile** [comment]
@Sav22999 i think you should reconsider about putting it on Fdroid. Fdroid Store is immensely popular in Open source community & they would love to see this very good app on fdroid.

..And surely it would increase outreach & popularityof Open source Sav Pdf Viewer Pro.

It would also help in  Translation of app in various languages in short span of time as most community members voluntarily help Translate open source apps available on Fdroid Store in various Languages available worldwide.

**Comment by Sav22999** [comment]
@ShareASmile @Pranab009 Yup, I know. (In fact another my app is on F-Droid).
I need to see if the library used in this app is compatible with F-Droid policy.

**Comment by Sav22999** [comment]
I opened an issue to request to add the app on F-Droid: https://gitlab.com/fdroid/rfp/-/issues/1858

**Comment by austinhuang0131** [comment]
fyi: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9913#note_701892370

> If I understand correctly, the app uses a very old version of pdfium from 2018. There are a plenty of [vulnerabilities in it](https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=PDFium&search_type=all&isCpeNameSearch=false). Could you comment on security risks?

**Comment by Pranab009** [comment]
This app is too good but security issues..
Is it really secure ??
Is it not possible to change its old 
pdfium base??

![Uploading Screenshot_20211031-225508_1.png…]()

**Comment by Sav22999** [comment]
Published !
