### ISSUE TITLE
bug: disappearing top bar on scrolling

### ISSUE THREAD

**Issue by dag7dev** [Sav22999/sav-pdf-viewer-pro#13]
If you tap the top bar, while the content is scrolling, the top bar dismisses itself automatically.

Steps:
- scroll a pdf (tap on screen, swipe up)
-tap on the bar
- scroll content will continue and top bar will be displayed for an invisible amount of time

**Comment by Sav22999** [comment]
It's not a bug, it's a correct behaviour. If you scroll the top bar automatically disappears, so if you tap while you're scrolling of course the top bar mist disappear 🤷‍♂️

What should be the behaviour in your mind? 🙂
