### ISSUE TITLE
Navigation Icons are too small 

### ISSUE THREAD

**Issue by idhirandar** [Sav22999/sav-pdf-viewer-pro#19]
In app navigation icons are too small 

Device :- Android 11

**Comment by Sav22999** [comment]
@idhirandar Could you send me a screenshot please? Thanks

**Comment by idhirandar** [comment]
> @idhirandar 

Sure, thank you for quick response

![Screenshot_20211030-225157.jpg](https://user-images.githubusercontent.com/71155874/139542949-3041b5bc-53d7-4104-99dc-bb50ca39366f.jpg)

**Comment by Sav22999** [comment]
Thanks!

I'll check and try to fix this issue. I'm sorry for the inconvenience
