### ISSUE TITLE
Latest release not on f-droid?

### ISSUE THREAD

**Issue by EpicGamer007** [Sav22999/sav-pdf-viewer-pro#23]
Saw recent update here on github but when looking on f-droid, I saw that it was still 1 version back, any plans on updating f-droid's version?

**Comment by Sav22999** [comment]
F-Deoid is auto-updated via GitHub, but they update with less frequency respect to the Google Play. So, I'm waiting the updating there too 😂

**Comment by EpicGamer007** [comment]
oh ok, thank you.
Great app by the way, it is very useful :)

**Comment by EpicGamer007** [comment]
Updated it yesterday :)
