### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Sav22999/sav-pdf-viewer-pro#36]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4099249912#L903

ref: https://github.com/Sav22999/sav-pdf-viewer-pro/blame/1.11/app/build.gradle#L11

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/68159fdf05abc3e23a40f1f2d9247ced9dc80893

**Comment by Sav22999** [comment]
@licaon-kter Thanks, I wrong the applicationId, sorry.
I've updated the master branch and the release, please confirm to me it works correctly

**Comment by licaon-kter** [comment]
You did not commit anything new (yet?)

**Comment by Sav22999** [comment]
@licaon-kter Can you see now ? 🤔

**Comment by Sav22999** [comment]
Maybe it was still loading

**Comment by licaon-kter** [comment]
Maybe I;m looking wrong?

Latest commit is https://github.com/Sav22999/sav-pdf-viewer-pro/commit/89fbd30a1dbd5acac8ccad776b406ea36294b92d

Tag 1.11 points to the same commit.

This commit has wrong appid: https://github.com/Sav22999/sav-pdf-viewer-pro/commit/89fbd30a1dbd5acac8ccad776b406ea36294b92d#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R11

**Comment by Sav22999** [comment]
@licaon-kter that was weird. Now I've updated with a fix (1.11.1), please let me know if the build compiles now

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/8a9cb6c93ba0b55152aa42701163b6ef0ed84820
