### ISSUE TITLE
F-Droid version not there/404 link

### ISSUE THREAD

**Issue by rugk** [Sav22999/sav-pdf-viewer-pro#41]
The Readme F-Droid link links to https://f-droid.org/it/packages/com.saverio.pdfviewer/
This returns 404.

Also I cannot manually find it: https://search.f-droid.org/?q=sav+pdf&lang=de

Ref https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.saverio.pdfviewer.yml

> KnownVuln as it uses a very old version of pdfium with many vulnerabilities,
    see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9913#note_701892370
    https://github.com/Sav22999/sav-pdf-viewer-pro/issues/28

Don't know whether it is because of this, but usually antifeatures are "just" displayed and do not prevent listing hmm?

**Comment by Sav22999** [comment]
@rugk oh, shit. I didn't know... and yes, it was displayed "antifeatures". 🤷‍♂️

I'll remove the link to F-Droid

**Comment by rugk** [comment]
I don't know we can also ask the F-Droid devs if it is not clear to anybody what is wrong here.

**Comment by Sav22999** [comment]
@rugk Do you want to do it? 😄

**Comment by rugk** [comment]
https://forum.f-droid.org/t/why-is-sav-pdf-viewer-pro-not-shown-anymore/23134?u=rugk

**Comment by rugk** [comment]
Answer:
> Apps using that PDF library were disabled as it wasn’t compiled from source (and is horrifically insecure).
>
>See [Mj pdf (!12658) · Merge requests · F-Droid / Data · GitLab](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12658#note_1363071726)

**Comment by Sav22999** [comment]
Close this issue because it's related to #28
