### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [Sav22999/sav-pdf-viewer-pro#53]
Please support the Android 13 Themed App Icons feature.

![Screenshot_2023-10-30-23-01-27-929_com miui home](https://github.com/Sav22999/sav-pdf-viewer-pro/assets/23485114/f24ee692-9065-4cae-adc6-cf7ed298ed10)

Thanks 🙏

**Comment by Sav22999** [comment]
@xmha97 Thank you for your feedback! I'll release an update with a new icon, which supports monochrome theme as well! 😄

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
Thanks, please release a new version.

**Comment by Sav22999** [comment]
@xmha97 I've already released a new version, although Google Have to approve it

**Comment by xmha97** [comment]
Thanks, I'm installing the new version from GitHub.
