### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [Sav22999/sav-pdf-viewer-pro#58]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by Sav22999** [comment]
@IzzySoft Sure! Thanks for the reporting.

Just released 1.15.1.2 as "release" and "signed"

Let me know if it's correct 😄

**Comment by IzzySoft** [comment]
Yes, that's fine, thanks! Just Github messed up the releases once more (it doesn't show up there; had to grab it manually going via tags :see_no_evil: This happens from time to time, was reported more than once but never got fixed. AFAIK it's triggered when you delete a release and re-create it at the very same tag/commit)

Solved then in record time, thanks a lot! :star_struck:

**Comment by IzzySoft** [comment]
Oh, PS: Please stick to these nice signed release APKs with future versions, too :smile:
